image: registry.gitlab.tugraz.at/vpu/webcomponents/common/main:v1

before_script:
  - "sed -i 's|git@gitlab.tugraz.at:VPU|../..|g' .gitmodules"
  - git submodule sync
  - git submodule update --init
stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run build-dev
    - npm run build
    - npm test

.deploy_defaults: &deploy_defaults
  stage: deploy
  script:
    # Add ssh key
    - mkdir -p ~/.ssh
    - echo "${DEPLOY_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa "${DEPLOY_HOST}" >> ~/.ssh/known_hosts
    # Install PHP dependencies
    - "composer require 'deployer/deployer: ^6.4' 'deployer/recipes: ^6.2'"
    # Deploy
    - ./vendor/bin/dep deploy "${DEPLOY_TARGET}"
    - echo "Deployed to ${DEPLOY_URL}"

deploy_demo:
  only:
    refs:
      - demo
  variables:
    DEPLOY_TARGET: demo
    DEPLOY_HOST: mw01-dev.tugraz.at
    DEPLOY_KEY: "$DEPLOY_SSH_KEY"
    DEPLOY_URL: https://frontend-demo.tugraz.at
  <<: *deploy_defaults

deploy_dev:
  only:
    refs:
      - master
  variables:
    DEPLOY_TARGET: dev
    DEPLOY_HOST: mw01-dev.tugraz.at
    DEPLOY_KEY: "$DEPLOY_SSH_KEY"
    DEPLOY_URL: https://mw-frontend-dev.tugraz.at
  <<: *deploy_defaults
