image: debian:buster

before_script:
  - apt update
  - apt install -y git
  - "sed -i 's|git@gitlab.tugraz.at:VPU|../..|g' .gitmodules"
  - git submodule sync
  - git submodule update --init

stages:
  - test

main:
  allow_failure: true
  stage: test
  script:
    - apt update
    - apt install -y npm
    - npm run setup
    - npm install
    - npm run build-dev
    - npm run build
